import { useEffect, useMemo, useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { currentUser, logout, pb } from '../lib/pocketbase';
import { canSupervise, canWorkTickets } from '../lib/roles';
import '../assets.css';

const TYPES = { laptop:'Laptop',desktop:'PC escritorio',monitor:'Monitor',telefono:'Teléfono',impresora:'Impresora',red:'Red',servidor:'Servidor',accesorio:'Accesorio',otro:'Otro' };
const STATES = { disponible:'Disponible',asignado:'Asignado',mantenimiento:'Mantenimiento',reparacion:'Reparación',baja:'Baja' };
const EMPTY = { asset_tag:'',type:'laptop',brand:'',model:'',serial_number:'',status:'disponible',assigned_to:'',department:'',location:'',purchase_date:'',warranty_until:'',purchase_cost:'',processor:'',ram:'',storage:'',operating_system:'',ip_address:'',mac_address:'',notes:'' };
function dateLabel(value){ if(!value)return '—'; return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(value)); }

export default function Assets(){
 const navigate=useNavigate(); const user=currentUser(); const mayView=canWorkTickets(user); const mayManage=canSupervise(user);
 const [assets,setAssets]=useState([]); const [users,setUsers]=useState([]); const [links,setLinks]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [search,setSearch]=useState(''); const [status,setStatus]=useState('todos'); const [type,setType]=useState('todos'); const [editing,setEditing]=useState(null); const [form,setForm]=useState(EMPTY); const [saving,setSaving]=useState(false);
 async function load(){ try{ const [a,u,l]=await Promise.all([pb.collection('hd_assets').getFullList({sort:'asset_tag',expand:'assigned_to'}),pb.collection('hd_users').getFullList({filter:'active = true',sort:'name,email'}),pb.collection('hd_asset_ticket_links').getFullList({sort:'-created',expand:'ticket,asset'})]); setAssets(a);setUsers(u);setLinks(l);setError(''); }catch(err){console.error(err);setError(err?.response?.message||err?.message||'No fue posible cargar el inventario.');}finally{setLoading(false);} }
 useEffect(()=>{if(mayView)load();},[mayView]);
 const stats=useMemo(()=>({total:assets.length,assigned:assets.filter(a=>a.status==='asignado').length,available:assets.filter(a=>a.status==='disponible').length,service:assets.filter(a=>['mantenimiento','reparacion'].includes(a.status)).length}),[assets]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return assets.filter(a=>(status==='todos'||a.status===status)&&(type==='todos'||a.type===type)&&(!q||[a.asset_tag,a.brand,a.model,a.serial_number,a.department,a.location,a.expand?.assigned_to?.name,a.expand?.assigned_to?.email].some(v=>String(v||'').toLowerCase().includes(q))));},[assets,search,status,type]);
 const ticketCount=useMemo(()=>{const map={};links.forEach(l=>{map[l.asset]=(map[l.asset]||0)+1;});return map;},[links]);
 function edit(asset){setEditing(asset);setForm({...EMPTY,...asset,assigned_to:asset.assigned_to||'',purchase_date:asset.purchase_date?.slice(0,10)||'',warranty_until:asset.warranty_until?.slice(0,10)||''});window.scrollTo({top:0,behavior:'smooth'});}
 function clear(){setEditing(null);setForm(EMPTY);}
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const payload={...form,purchase_cost:form.purchase_cost?Number(form.purchase_cost):0,assigned_to:form.assigned_to||'',purchase_date:form.purchase_date||'',warranty_until:form.warranty_until||''};if(payload.assigned_to&&payload.status==='disponible')payload.status='asignado';if(editing)await pb.collection('hd_assets').update(editing.id,payload);else await pb.collection('hd_assets').create(payload);setSuccess(editing?'Activo actualizado.':'Activo registrado.');clear();await load();setTimeout(()=>setSuccess(''),2500);}catch(err){console.error(err);setError(err?.response?.message||err?.message||'No fue posible guardar el activo.');}finally{setSaving(false);}}
 function handleLogout(){logout();navigate('/login');}
 if(!mayView)return <Navigate to="/" replace/>;
 return <main className="app-shell"><aside className="sidebar"><div><p className="eyebrow">MARTCOM</p><h2>Soporte IT</h2><nav>{mayManage&&<a onClick={()=>navigate('/')}>Dashboard</a>}<a onClick={()=>navigate('/tickets/new')}>Crear ticket</a><a onClick={()=>navigate('/tickets/mine')}>Mis tickets</a><a onClick={()=>navigate('/support')}>Panel de soporte</a>{mayManage&&<a onClick={()=>navigate('/reports')}>Reportes</a>}<a className="active">Activos IT</a></nav></div><button className="secondary" onClick={handleLogout}>Cerrar sesión</button></aside><section className="content">
 <header className="topbar"><div><p className="muted">Inventario · Tecnología</p><h1>Activos IT</h1><p className="muted">Equipos, asignaciones, garantía e historial de incidencias.</p></div>{mayManage&&<button onClick={clear}>+ Nuevo activo</button>}</header>
 {error&&<div className="error">{error}</div>}{success&&<div className="success">{success}</div>}
 <div className="stats-grid asset-kpis"><article className="card"><span>Total</span><strong>{stats.total}</strong></article><article className="card"><span>Asignados</span><strong>{stats.assigned}</strong></article><article className="card"><span>Disponibles</span><strong>{stats.available}</strong></article><article className="card"><span>Mantenimiento / reparación</span><strong>{stats.service}</strong></article></div>
 {mayManage&&<form className="card asset-form" onSubmit={save}><div className="asset-form-head"><div><p className="eyebrow">{editing?'EDITAR ACTIVO':'ALTA DE ACTIVO'}</p><h2>{editing?editing.asset_tag:'Registrar equipo'}</h2></div>{editing&&<button type="button" className="secondary" onClick={clear}>Cancelar edición</button>}</div><div className="asset-fields">
  <label>Etiqueta / ID<input required value={form.asset_tag} onChange={e=>setForm({...form,asset_tag:e.target.value})} placeholder="MARTCOM-LAP-001"/></label><label>Tipo<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Marca<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></label><label>Modelo<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Número de serie<input value={form.serial_number} onChange={e=>setForm({...form,serial_number:e.target.value})}/></label><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(STATES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Usuario asignado<select value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value="">Sin asignar</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.email}</option>)}</select></label><label>Departamento<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>Ubicación<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Oficina / piso / posición"/></label><label>Compra<input type="date" value={form.purchase_date} onChange={e=>setForm({...form,purchase_date:e.target.value})}/></label><label>Garantía hasta<input type="date" value={form.warranty_until} onChange={e=>setForm({...form,warranty_until:e.target.value})}/></label><label>Costo<input type="number" min="0" step="0.01" value={form.purchase_cost} onChange={e=>setForm({...form,purchase_cost:e.target.value})}/></label><label>Procesador<input value={form.processor} onChange={e=>setForm({...form,processor:e.target.value})}/></label><label>RAM<input value={form.ram} onChange={e=>setForm({...form,ram:e.target.value})} placeholder="16 GB DDR5"/></label><label>Almacenamiento<input value={form.storage} onChange={e=>setForm({...form,storage:e.target.value})} placeholder="512 GB SSD"/></label><label>Sistema operativo<input value={form.operating_system} onChange={e=>setForm({...form,operating_system:e.target.value})}/></label><label>IP<input value={form.ip_address} onChange={e=>setForm({...form,ip_address:e.target.value})}/></label><label>MAC<input value={form.mac_address} onChange={e=>setForm({...form,mac_address:e.target.value})}/></label><label className="asset-notes">Notas<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
 </div><div className="asset-form-actions"><button disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Registrar activo'}</button></div></form>}
 <div className="card asset-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar etiqueta, serie, marca, modelo, usuario, área…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos los estados</option>{Object.entries(STATES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="todos">Todos los tipos</option>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
 <article className="card asset-table-wrap">{loading?<p className="muted">Cargando inventario…</p>:<table className="asset-table"><thead><tr><th>Activo</th><th>Equipo</th><th>Serie</th><th>Estado</th><th>Asignado a</th><th>Ubicación</th><th>Garantía</th><th>Tickets</th>{mayManage&&<th>Acciones</th>}</tr></thead><tbody>{filtered.length?filtered.map(a=><tr key={a.id}><td><strong>{a.asset_tag}</strong><span>{TYPES[a.type]||a.type}</span></td><td><strong>{[a.brand,a.model].filter(Boolean).join(' ')||'—'}</strong><span>{[a.processor,a.ram,a.storage].filter(Boolean).join(' · ')}</span></td><td>{a.serial_number||'—'}</td><td><span className={`asset-status status-${a.status}`}>{STATES[a.status]||a.status}</span></td><td>{a.expand?.assigned_to?.name||a.expand?.assigned_to?.email||'Sin asignar'}</td><td>{[a.department,a.location].filter(Boolean).join(' · ')||'—'}</td><td>{dateLabel(a.warranty_until)}</td><td><button className="link-button" onClick={()=>navigate(`/assets/${a.id}`)}>{ticketCount[a.id]||0} historial</button></td>{mayManage&&<td><button className="secondary compact" onClick={()=>edit(a)}>Editar</button></td>}</tr>):<tr><td colSpan={mayManage?9:8} className="asset-empty">No hay activos que coincidan con los filtros.</td></tr>}</tbody></table>}</article>
 </section></main>;
}
